// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-accounts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/result.ts
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : fail("Not authenticated. Connect this MCP server with your LifeSync account.");
}

// src/lib/mcp/tools/list-accounts.ts
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List the signed-in user's money accounts (name, type and current balance).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    const { data, error } = await supabaseForUser(ctx).from("accounts").select("id, name, type, current_balance, balance, is_active").order("name", { ascending: true });
    if (error) return fail(error.message);
    return ok({
      accounts: (data ?? []).map((a) => ({
        id: a.id,
        name: a.name,
        type: a.type,
        balance: a.current_balance ?? a.balance ?? 0,
        is_active: a.is_active
      }))
    });
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's recent transactions, optionally filtered by date range, type or category.",
  inputSchema: {
    from: z.string().optional().describe("Earliest transaction date, YYYY-MM-DD."),
    to: z.string().optional().describe("Latest transaction date, YYYY-MM-DD."),
    type: z.enum(["income", "expense", "transfer"]).optional().describe("Only return transactions of this type."),
    category: z.string().optional().describe("Exact category name to filter by."),
    limit: z.number().int().optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, type, category, limit }, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    const rows = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("transactions").select(
      "id, transaction_date, type, amount, category, description, payment_mode, account_id"
    ).order("transaction_date", { ascending: false }).limit(rows);
    if (from) query = query.gte("transaction_date", from);
    if (to) query = query.lte("transaction_date", to);
    if (type) query = query.eq("type", type);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, transactions: data ?? [] });
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var create_transaction_default = defineTool3({
  name: "create_transaction",
  title: "Record a transaction",
  description: "Record an income or expense transaction for the signed-in user. Use list_accounts first to pick an account.",
  inputSchema: {
    account_id: z2.string().describe("Account UUID from list_accounts."),
    type: z2.enum(["income", "expense"]).describe("Whether money came in or went out."),
    amount: z2.number().positive().describe("Positive amount in the user's currency."),
    category: z2.string().describe("Category name, e.g. Groceries or Salary."),
    description: z2.string().optional().describe("Short note about the transaction."),
    transaction_date: z2.string().optional().describe("Date as YYYY-MM-DD. Defaults to today."),
    payment_mode: z2.string().optional().describe("How it was paid, e.g. UPI, Cash, Card.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    const userId = ctx.getUserId();
    if (!userId) return fail("Could not resolve the signed-in user.");
    const { data, error } = await supabaseForUser(ctx).from("transactions").insert({
      user_id: userId,
      account_id: input.account_id,
      type: input.type,
      amount: input.amount,
      category: input.category,
      description: input.description ?? null,
      payment_mode: input.payment_mode ?? null,
      transaction_date: input.transaction_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      source_module: "mcp"
    }).select("id, transaction_date, type, amount, category, description").single();
    if (error) return fail(error.message);
    return ok({ transaction: data });
  }
});

// src/lib/mcp/tools/spending-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var spending_summary_default = defineTool4({
  name: "spending_summary",
  title: "Spending summary",
  description: "Summarise the signed-in user's income, expenses and per-category spending for a month (YYYY-MM).",
  inputSchema: {
    month: z3.string().optional().describe("Month as YYYY-MM. Defaults to the current month.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    const target = /^\d{4}-\d{2}$/.test(month ?? "") ? month : (/* @__PURE__ */ new Date()).toISOString().slice(0, 7);
    const [year, mon] = target.split("-").map(Number);
    const start = `${target}-01`;
    const end = new Date(Date.UTC(year, mon, 0)).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("transactions").select("type, amount, category").gte("transaction_date", start).lte("transaction_date", end);
    if (error) return fail(error.message);
    let income = 0;
    let expense = 0;
    const byCategory = {};
    for (const row of data ?? []) {
      const amount = Number(row.amount) || 0;
      if (row.type === "income") income += amount;
      else if (row.type === "expense") {
        expense += amount;
        byCategory[row.category] = (byCategory[row.category] ?? 0) + amount;
      }
    }
    const categories = Object.entries(byCategory).map(([category, total]) => ({ category, total })).sort((a, b) => b.total - a.total);
    return ok({
      month: target,
      income,
      expense,
      net: income - expense,
      transaction_count: data?.length ?? 0,
      top_categories: categories.slice(0, 10)
    });
  }
});

// src/lib/mcp/tools/list-bills.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_bills_default = defineTool5({
  name: "list_bills",
  title: "List bills",
  description: "List the signed-in user's bills and subscriptions with amounts, due dates and paid status.",
  inputSchema: {
    unpaid_only: z4.boolean().optional().describe("When true, return only bills that are not marked paid.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unpaid_only }, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    let query = supabaseForUser(ctx).from("bills").select("id, name, provider, amount, due_date, billing_cycle, is_paid, status").order("due_date", { ascending: true });
    if (unpaid_only) query = query.eq("is_paid", false);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, bills: data ?? [] });
  }
});

// src/lib/mcp/tools/list-goals.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_goals_default = defineTool6({
  name: "list_goals",
  title: "List goals",
  description: "List the signed-in user's goals with progress and target dates.",
  inputSchema: {
    include_completed: z5.boolean().optional().describe("When true, also return goals already completed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_completed }, ctx) => {
    const unauthed = requireAuth(ctx);
    if (unauthed) return unauthed;
    let query = supabaseForUser(ctx).from("goals").select("id, title, description, category, target_date, progress, is_completed").order("target_date", { ascending: true });
    if (!include_completed) query = query.eq("is_completed", false);
    const { data, error } = await query;
    if (error) return fail(error.message);
    return ok({ count: data?.length ?? 0, goals: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "evdqvwqruclcdxbeztnd";
var mcp_default = defineMcp({
  name: "budget-buddy",
  title: "Budget Buddy",
  version: "0.1.0",
  instructions: "Tools for the LifeSync personal finance app. Use list_accounts to find account IDs, list_transactions and spending_summary to review money movement, create_transaction to record income or expenses, and list_bills / list_goals for upcoming bills and goal progress. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_accounts_default,
    list_transactions_default,
    create_transaction_default,
    spending_summary_default,
    list_bills_default,
    list_goals_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
