// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

type PublicRuntimeEnv = {
  VITE_SUPABASE_API_URL?: string;
  VITE_SUPABASE_URL?: string;
  VITE_SUPABASE_PUBLISHABLE_KEY?: string;
  VITE_SUPABASE_ANON_KEY?: string;
};

declare global {
  interface Window {
    __ENV?: PublicRuntimeEnv;
  }
}

function configuredValue(...values: Array<string | undefined>): string {
  return values.find((value) => value?.trim())?.trim() ?? '';
}

function resolveSupabaseUrl(value: string): string {
  const trimmed = value.trim().replace(/\/+$/, '');
  if (/^https?:\/\//i.test(trimmed)) return trimmed;
  if (trimmed.startsWith('/') && typeof window !== 'undefined') {
    return new URL(trimmed, window.location.origin).toString().replace(/\/+$/, '');
  }
  return trimmed;
}

const runtimeEnv = typeof window !== 'undefined' ? window.__ENV : undefined;

const SUPABASE_URL = resolveSupabaseUrl(configuredValue(
  runtimeEnv?.VITE_SUPABASE_API_URL,
  import.meta.env.VITE_SUPABASE_API_URL,
  runtimeEnv?.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_URL,
));
const SUPABASE_PUBLISHABLE_KEY = configuredValue(
  runtimeEnv?.VITE_SUPABASE_PUBLISHABLE_KEY,
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  runtimeEnv?.VITE_SUPABASE_ANON_KEY,
  import.meta.env.VITE_SUPABASE_ANON_KEY,
);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Supabase is not configured. Add VITE_SUPABASE_URL (or VITE_SUPABASE_API_URL) and VITE_SUPABASE_PUBLISHABLE_KEY to your .env file.',
  );
}


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
